# Generated by Django 4.0.6 on 2022-07-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estadoCivil',
        ),
    ]
